### ISSUE TITLE
Atom serial numbers wrap at 9999

### ISSUE THREAD

**Issue by DocKDE** [nonnominandus/pdbtbx#51] opened 2021-03-19 16:11 UTC
Okay, last one for today:
I noticed the atom serial number in the PDB struct wraps around at 9999 even if that's not the case in the input PDB file. Is this standard behavior? Because I seem to recall that 5 columns are reserved for this value so it could contain larger numbers, no?
Is that something that could be changed with a separate method or an argument?
Sorry for pestering you lately.
Have a great weekend!

**Comment by nonnominandus** [comment] 2021-03-19 16:31
According to the wwPDB v3.30 definition of PDB files atom serial numbers cannot exceed 99999, so you are totally correct. I probably misread the definition (something about ranges including or excluding the last number and 0 based or 1 based indexing), so the both the validation and parsing of PDB files were erroneous. The problem is fixed now and I will release a patch on crates.io to make it easy for you to work with your files.

**Closed** 2021-03-19 16:34 UTC
